source: .
destination:     ./_site
collections_dir: .
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes

exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - nuget/
  - less/
  - vendor/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - sache.json
  - twbsconfig.yml
  - server.js
  - .c9/
  
site:
  authors:
    - Fredrick Rogers